apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
    - name: mnt-inputs
      mountPath: /data
      readOnly: false
  serviceAccountName: ssiog-runner-ksa
  volumes:
  - name: mnt-inputs
    csi:
      driver: gcsfuse.csi.storage.gke.io
      readOnly: false
      volumeAttributes:
        bucketName: "princer-ssiog-data-bkt"
        mountOptions: "debug_fuse,implicit-dirs,metadata-cache:ttl-secs:-1,metadata-cache:stat-cache-max-size-mb:-1,metadata-cache:type-cache-max-size-mb:-1"