apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  serviceAccountName: princer-ssiog-ksa-e2892743606541ae
  containers:
  - name: test-pod
    image: google/cloud-sdk:slim
    command: ["sleep","infinity"]
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 10Mi